language: elixir
elixir:
  - 1.1.0
otp_release:
  - 18.1
sudo: false # to use faster container based build environment
env:
  - ELIXIR_ERL_OPTIONS=""
  - ELIXIR_ERL_OPTIONS="+T 9"
script:
  - mix test
